import * as continuum from "../../../src/core/Continuum";
import * as stage from "../../../src/core/Stage";

var log = require('winston');
log.level = 'error';


export interface ProcessingStageInterface extends stage.Stage {// Auto generated by tool connecting to ServiceBroker
    thingWasProcessed: boolean;
    doThing: (v: string) => void;
    processData: (continuum: continuum.ContinuumBase,
                  pss: ProcessingStageInterface, params: any) => void;// Should be Continuum not ContinuumBase
}

export class ProcessingStage extends stage.Stage implements ProcessingStageInterface {
    public thingWasProcessed: boolean = false; // Used for tests.

    public doThing(v: string) {
        log.info("ProcessingStage: processing data '" + v + "'");

        // Allow tests to verify function ran.
        this.thingWasProcessed = true;
    }

    public processData;
}