import * as continuum from "../../../src/core/Continuum";
import * as stage from "../../../src/core/Stage";

var log = require('winston');
log.level = 'error';


export class DbStage extends stage.Stage implements DbStageInterface {
    public getThing(k: string): string {
        return "cow";
    }
    public cacheAndProcessData; // Pick up global function and hang off interface to stage
}

export interface DbStageInterface extends stage.Stage { // Auto generated by tool connecting to ServiceBroker
    getThing(k: string): string
    cacheAndProcessData: (continuum: continuum.ContinuumBase,
                          dbs: DbStageInterface, params: any) => void; // Should be Continuum not ContinuumBase 
}

